logging:
  level:
    com.thaisoftplus: DEBUG
spring:
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update